name: Push Run
on: [push]

# Job lists of the workflow
# This job requires the OS to be run as follows
# It also starts to install JDK before tests

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        id: jdk
        uses: actions/setup-java@v3.10.0

      - name: Set up Maven
        id: maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2

      # Cache the maven packages to make the run fast
      - name: Cache the Maven packages
        id: cache_maven
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Tests
        id: runtest
        run: mvn test

      - name: Upload Full Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Full Report
          path: ${{ github.workspace }}/test-output/SparkReport




